### ISSUE TITLE
Add healthcheck endpoint

### ISSUE THREAD

**Issue by BlakeWilliams** [BlakeWilliams/viewproxy#10]
We should add an endpoint that returns a simple response so internal and external services can validate that viewproxy is still up and running.

**Comment by aaronbbrown** [comment]
The `HEALTHCHECK` in the Dockerfile won't do anything under Kubernetes. You'll want a readiness probe and to follow the guidelines in https://moda.githubapp.com/docs/features/pod-lifecycle/.

**Comment by BlakeWilliams** [comment]
A simple version of this was added in https://github.com/BlakeWilliams/viewproxy/pull/38, closing
