### ISSUE TITLE
Expose a hook to measure/log the full request

### ISSUE THREAD

**Issue by iancanderson** [BlakeWilliams/viewproxy#29]
Similarly to `PreRequest`, we could have a `PostRequest` hook. We could provide timing in that function.

Alternatively, we could expose an `AroundRequest` hook and let the "host" code do the measurement.

**Comment by BlakeWilliams** [comment]
@iancanderson I think providing an `AroundRequest` hook might be more flexible, so I'm 👍 on deprecating/removing `PreRequest` in favor of `AroundRequest`.
